//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Implyzer;

#nullable enable

public enum ImplKind {
    ReferenceType,
    ValueType
}

[AttributeUsage(AttributeTargets.Interface)]
public sealed class ImplTypeAttribute : Attribute {
    public ImplTypeAttribute(ImplKind kind) {
        Kind = kind;
    }

    public ImplTypeAttribute(Type baseType) {
        Kind = ImplKind.ReferenceType;
        BaseType = baseType;
    }

    public ImplKind Kind { get; }
    public Type? BaseType { get; }
}

#nullable restore