//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Implyzer;

#nullable enable

internal enum ImplKind {
    ReferenceType,
    ValueType,
    ReferenceTypeNew
}

/// <summary>
/// Represents an attribute that specifies the implementation type requirements for an interface.
/// This attribute is used to enforce that implementations of the decorated interface
/// must adhere to specific constraints, such as being a reference type, value type,
/// or inheriting from a specific base type.
/// The attribute can be applied to interfaces only.
/// </summary>
[AttributeUsage(AttributeTargets.Interface)]
internal sealed class ImplTypeAttribute : Attribute {
    public ImplTypeAttribute(ImplKind kind) {
        Kind = kind;
    }

    public ImplTypeAttribute(Type baseType) {
        Kind = ImplKind.ReferenceType;
        BaseType = baseType;
    }

    public ImplKind Kind { get; }
    public Type? BaseType { get; }
}

#nullable restore