//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Implyzer;

[AttributeUsage(AttributeTargets.Interface)]
internal class IndirectImplAttribute : Attribute {
    public Type ImplementInstead { get; }
    
    public IndirectImplAttribute(Type implementInstead) {
        ImplementInstead = implementInstead;
    }
}