//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Implyzer;

/// <summary>
/// Indicates that the decorated interface should not be implemented directly,
/// but rather using a different interface. This is useful for forcing implementation
/// of a generic version of an interface instead of a non-generic one.
/// </summary>
[AttributeUsage(AttributeTargets.Interface)]
public class IndirectImplAttribute : Attribute {
    public Type ImplementInstead { get; }
    
    public IndirectImplAttribute(Type implementInstead) {
        ImplementInstead = implementInstead;
    }
}