//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using static System.AttributeTargets;

namespace Implyzer;

#nullable enable

/// <summary>
/// Indicates that the decorated symbol should be replaced by another symbol.
/// This is similar to [Obsolete], but allows specifying a strong-typed replacement
/// or a free-form string suggestion without necessarily marking the symbol as obsolete/deprecated
/// in the compiler's eyes (though it generates a suggestion diagnostic).
/// </summary>
[AttributeUsage(All & ~(ReturnValue | Assembly | GenericParameter | Module | Parameter), Inherited = false, AllowMultiple = false)]
internal sealed class UseInsteadAttribute : Attribute {
    
    /// <summary>
    /// Initializes a new instance of the <see cref="UseInsteadAttribute"/> class
    /// specifying a replacement type.
    /// </summary>
    /// <param name="replacementType">The type that should be used instead.</param>
    public UseInsteadAttribute(Type replacementType) {
        ReplacementType = replacementType;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="UseInsteadAttribute"/> class
    /// specifying a replacement type and a specific member name.
    /// </summary>
    /// <param name="replacementType">The type that contains the replacement member.</param>
    /// <param name="memberName">The name of the member to use instead.</param>
    public UseInsteadAttribute(Type replacementType, string memberName) {
        ReplacementType = replacementType;
        MemberName = memberName;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="UseInsteadAttribute"/> class
    /// specifying a replacement type and its constructor parameter types.
    /// </summary>
    /// <param name="replacementType">The type to use.</param>
    /// <param name="parameterTypes">The parameter types of the specific constructor to use.</param>
    public UseInsteadAttribute(Type replacementType, Type[] parameterTypes) {
        ReplacementType = replacementType;
        ParameterTypes = parameterTypes;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="UseInsteadAttribute"/> class
    /// specifying a replacement suggestion string.
    /// </summary>
    /// <param name="replacement">The suggestion of what to use instead.</param>
    public UseInsteadAttribute(string replacement) {
        ReplacementString = replacement;
    }

    public Type? ReplacementType { get; set; }
    public string? MemberName { get; set; }
    public Type[]? ParameterTypes { get; set; }
    public string? ReplacementString { get; set; }
}

#nullable restore