<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net5.0</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>exe</OutputType>

        <LocalPackagingTest>false</LocalPackagingTest>
    </PropertyGroup>

    <ItemGroup Condition="'$(LocalPackagingTest)' == 'false'">
        <ProjectReference Include="..\Src\Implyzer\Implyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </ProjectReference>
        <ProjectReference Include="..\Src\Implyzer.CodeFixes\Implyzer.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup Condition="'$(LocalPackagingTest)' == 'true'">
        <PackageReference Include="Implyzer" Version="2026.4.1" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
