//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Implyzer {

    /// <summary>
    /// Specifies that static virtual methods defined on interfaces should have their default
    /// implementations generated directly inside target implementing types.
    /// When applied to an interface, all static virtual methods on that interface are generated in implementing types.
    /// When applied to a class or struct, static virtual methods from all implemented interfaces are generated inside it.
    /// When applied at assembly level, applies globally across all interfaces and implementing types.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Assembly, Inherited = false, AllowMultiple = false)]
    public sealed class ImplementInTargetTypesAttribute : Attribute {

        public bool Enabled { get; }

        public ImplementInTargetTypesAttribute(bool enabled = true) {
            Enabled = enabled;
        }
    }

}

#nullable restore
