//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Implyzer {

    public enum ImplKind {
        
        /// <summary>
        /// Specifies that the implementation must be of a reference type.
        /// Use this value to enforce that the target interface can only be implemented by classes,
        /// excluding structs and other non-reference types.
        /// </summary>
        ReferenceType,

        /// <summary>
        /// Specifies that the implementation must be of a value type.
        /// Use this value to enforce that the target interface can only be implemented by structs or
        /// other non-reference types, excluding classes and other reference types.
        /// </summary>
        ValueType,
        
        /// <summary>
        /// Specifies that the implementation must be of a reference type.
        /// Use this value to enforce that the target interface can only be implemented by classes,
        /// excluding structs and other non-reference types. In addition, the implementation must contain a
        /// constructor that takes no arguments.
        /// </summary>
        ReferenceTypeNew
    }

    /// <summary>
    /// Represents an attribute that specifies the implementation type requirements for an interface.
    /// This attribute is used to enforce that implementations of the decorated interface
    /// must adhere to specific constraints, such as being a reference type, value type,
    /// or inheriting from a specific base type.
    /// The attribute can be applied to interfaces only.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface)]
    public sealed class ImplTypeAttribute : Attribute {
    
        public ImplTypeAttribute(ImplKind kind) {
            Kind = kind;
        }

        public ImplTypeAttribute(Type baseType) {
            Kind     = ImplKind.ReferenceType;
            BaseType = baseType;
        }

        public ImplKind Kind     { get; }
        public Type?    BaseType { get; }
    }
}

#nullable restore