//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;
using System.Collections.Generic;

namespace Implyzer {

    /// <summary>
    /// An attribute applied to an interface to enforce implementation of a static method
    /// with a specified name and signature. This feature can be used as a replacement
    /// for the `static abstract` feature in C# for older runtime versions.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = true)]
    public sealed class StaticAbstractAttribute : Attribute {
    
        public Type?                      TargetClass { get; }
        public string                     MethodName  { get; }
        public Type                       Signature   { get; }
        public Dictionary<string, string> TypeParams  { get; }
        
        public StaticAbstractAttribute(string methodName, Type signature, params string[] typeParams) {
            MethodName  = methodName;
            Signature   = signature;
            TypeParams  = ToDictionary(typeParams);
            TargetClass = null;
        }
    
        public StaticAbstractAttribute(string methodName, Type signature, Type targetClass, params string[] typeParams) {
            MethodName  = methodName;
            Signature   = signature;
            TypeParams  = ToDictionary(typeParams);
            TargetClass = targetClass;
        }

        private static Dictionary<string, string> ToDictionary(string[]? array) {
            var dict = new Dictionary<string, string>();
            if (array != null) {
                for (int i = 0; i < array.Length; i += 2) {
                    if (i + 1 < array.Length) {
                        dict[array[i]] = array[i + 1];
                    }
                }
            }
            return dict;
        }
    }
}

#nullable restore