//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Implyzer {

    /// <summary>
    /// Registers external types (e.g., BCL types or third-party library types)
    /// to the static abstract registry of an interface, provided they structurally
    /// implement all required static abstract members.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    public sealed class StaticRegisterAttribute : Attribute {

        /// <summary>
        /// Types to be structurally verified and registered to the interface.
        /// </summary>
        public Type[] Types { get; }

        /// <summary>
        /// When applied at the assembly level, specifies the target interface.
        /// Can also be specified as the first argument in the constructor at assembly level.
        /// </summary>
        public Type? TargetInterface { get; set; }

        /// <summary>
        /// If true (default), reports a compile-time error if a registered type does not
        /// implement all required members. If false, non-conforming types are ignored.
        /// </summary>
        public bool Strict { get; set; } = true;

        /// <summary>
        /// Registers one or more external types to the interface decorated with this attribute,
        /// or targeting an interface when applied at the assembly level.
        /// </summary>
        public StaticRegisterAttribute(params Type[] types) {
            Types = types ?? Type.EmptyTypes;
        }
    }

}

#nullable restore
