//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Implyzer {

    /// <summary>
    /// An attribute applied to an interface to declare a static virtual method
    /// with a specified name, signature, and default implementation.
    /// In C# 11+, this emits a `static virtual` interface member. On older runtime
    /// versions, it provides companion routing helpers with fallback to the default implementation.
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = true)]
    public sealed class StaticVirtualAttribute : StaticAbstractAttribute {

        public StaticVirtualAttribute(string methodName, Type signature, params string[] typeParams)
            : base(methodName, signature, typeParams) {
        }

        public StaticVirtualAttribute(string methodName, Type signature, Type targetClass, params string[] typeParams)
            : base(methodName, signature, targetClass, typeParams) {
        }
    }

}

#nullable restore
