//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Implyzer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System;

namespace Implyzer {

    /// <summary>
    /// An attribute applied to a static method to designate it as the default implementation
    /// for a static abstract/virtual interface method.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = false)]
    public sealed class StaticDefaultAttribute : Attribute {

        public string? MethodName { get; }

        public StaticDefaultAttribute(string? methodName = null) {
            MethodName = methodName;
        }
    }

}

#nullable restore
